# Use this file to create an Anaconda environment with:
# %> mamba env create -f environment.yaml [-n better_name]

# It does NOT install argos itself, so you can use this as a development environment.

# It installs the minimal supported version of Python, Qt, Numpy and PyQtGraph.
# See
#    https://numpy.org/neps/nep-0029-deprecation_policy.html#drop-schedule
#    https://github.com/pyqtgraph/pyqtgraph#qt-bindings-test-matrix

name: argosmin
channels:
  - conda-forge

dependencies:
  - python = 3.8
  - numpy = 1.20
  - pyqt = 5.15
  - h5py
  - netcdf4
  - pillow
  - scipy
  - pandas
  - pyqtgraph >= 0.12.4  # Otherwise LinePlot gives The truth value of an array with more than one element is ambiguous.
  - conda-forge::cmlib >= 1.1.3
  - conda-forge::pgcolorbar >= 1.1.3


# The following dependencies are for development only and therefore have no version number
  - mypy
  - pylint
  - sphinx
  - sphinx_rtd_theme
