#!/usr/bin/env bash

# Creates the HTML documentation, including the autogenerated API docs.
# Autogenerates API documentation. Creates .rst files in the api directory from the doc strings.

# TODO:
#   Where to put documentation for __init__ functions?
#   How to document type vars like Selection?
#   How to get rid of full module paths in table of contents?
#       add_module_names seems to do the trick, except for 'class in package.path.to.module)
#   How to get rid of full module path in parameter definitions?
#       Fixed in Sphinx 4.4 with autodoc_typehints_format
#       https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_typehints_format
#
# https://github.com/sphinx-doc/sphinx/issues/4257


# DWF_Library.rst (special members == __init__)

set -eux

ROOT_DIR=..
PACKAGE_DIR="${ROOT_DIR}/argos"
OUTPUT_DIR="source/api"

make clean
rm -rf "${OUTPUT_DIR}"

export PYTHONPATH="${ROOT_DIR}"

EXCLUDE="${PACKAGE_DIR}/external"
sphinx-apidoc --no-toc --module-first --separate -o "${OUTPUT_DIR}" "${PACKAGE_DIR}" "${EXCLUDE}"
make html
