#!/usr/bin/env bash

# Creates the HTML documentation, including the autogenerated API docs.
# Autogenerates API documentation. Creates .rst files in the api directory from the doc strings.

# Solved:
#   Where to put documentation for __init__ functions?
#       Used: autodoc_class_signature = "separated"
#       Did not use "special members == __init__" (as in pydwf_api/DwfLibrary.rst), which includes
#       dunder methods.
#   How to get rid of full module paths in table of contents?
#       add_module_names seems to do the trick, except for 'class in package.path.to.module)
#   How to get rid of full module path in parameter definitions?
#       Fixed in Sphinx 4.4 with autodoc_typehints_format. In Sphinx 5.0 the default is "short"
#       https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_typehints_format

# TODO:

#   Look at suppress_warnings to get rid of PyQt import warnings?

#   How to document type vars like Selection?
#       Perhaps with autodoc_type_aliases
#       https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_type_aliases

#   Look at autodoc_preserve_defaults when using default arguments.
#       https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_preserve_defaults

#   Look at autodoc_inherit_docstrings to reuse doc strings.
#       https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_inherit_docstrings

#   Look at Napo options:
#      https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html#module-sphinx.ext.napoleon


#   Look at Intersphinx:
#       https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html



set -eux

ROOT_DIR=..
PACKAGE_DIR="${ROOT_DIR}/argos"
OUTPUT_DIR="source/api"

make clean
rm -rf "${OUTPUT_DIR}"

export PYTHONPATH="${ROOT_DIR}"

EXCLUDE="${PACKAGE_DIR}/external"
sphinx-apidoc --no-toc --module-first --separate -o "${OUTPUT_DIR}" "${PACKAGE_DIR}" "${EXCLUDE}"
make html
